<a href="https://colab.research.google.com/github/gouravsingh2009/DECISION-TREE-ALGO-/blob/main/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy
import numpy as np 
from numpy import *

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
a = array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
b= array(([1,2,3],[4,5,6]))
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c =array([[[1,2,3],[1,2]],[[5,7,9],[2,8]]])
print(c)

<ipython-input-22-db9bedc6d192>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c =array([[[1,2,3],[1,2]],[[5,7,9],[2,8]]])


Check Number of Dimensions 

In [ ]:
a = array(42)
b = array([1, 2, 3, 4, 5])
c = array([[1, 2, 3], [4, 5, 6]])
d = array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
arr = array([1, 2, 3, 4], ndmin=2)

print(arr)
print('number of dimensions :', arr.ndim)

[[1 2 3 4]]
number of dimensions : 2


In [ ]:
print(d[0])
print(b[0])
print(c[1])

[[1 2 3]
 [4 5 6]]
1
[4 5 6]


Access elements in a multidimensional array 

In [ ]:
print(d[0,1])

[4 5 6]


In [ ]:
arr = array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


NEGATIVE INDEXING ( Using above array ' arr' .)

In [ ]:
print(arr[1,-3])

8


Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [13]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d[1:])
print(d[0:1])
print(d[1:0])

[[[1 2 3]
  [4 5 6]]]
[[[1 2 3]
  [4 5 6]]]
[]


In [ ]:
a= array([1,2,3,4,5,6,7,9])
print(a[4:7])
print(a[2:])
print(a[:5])
print(a[2:7:2])
print(a[-7:-1:2])
print(a[::3])

[5 6 7]
[3 4 5 6 7 9]
[1 2 3 4 5]
[3 5 7]
[2 4 6]
[1 4 7]


Slicing in 2 D Arrays 

In [ ]:
arr = array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

arr = array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[3 8]
[[2 3 4]
 [7 8 9]]


Methods for NUMPYS

In [ ]:
import numpy as np

arr_zeros= np.zeros(3)
arr_zeros


array([0., 0., 0.])

In [ ]:
arr_ones= np.ones([3,3])
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr_empty= np.empty((2,2))
arr_empty

array([[5.e-324, 5.e-324],
       [5.e-324, 0.e+000]])

In [ ]:
new_arr= np.arange(10)
print(new_arr)

[0 1 2 3 4 5 6 7 8 9]


Linspace for equally spaced elements

In [ ]:
np_linspce = np.linspace(1,5,8)
np_linspce

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [ ]:
r= np.arange(16)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
print(r.reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
print(r.reshape(2,2,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


Shape Manipulation 

In [11]:
import numpy as np
a = np.linspace(15,1,5)
print(a)
b= np.arange(1,10,3)
print(b)

[15.  11.5  8.   4.5  1. ]
[1 4 7]


In [25]:
#convert 1d array into 2d or 3 d array 

a = np.linspace(0,10)
print(a.ndim)
print(a.shape)
print(a)
b=a.reshape(5,10)
print(a.reshape(5,10))
print(a.reshape(2,5,5))
a.ravel
print(a)

1
(50,)
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
   1.2244898   1.42857143  1.63265306  1.83673469]
 [ 2.04081633  2.24489796  2.44897959  2.65306122  2.85714286  3.06122449
   3.26530612  3.46938776  3.67346939  3.87755102]
 [ 4.08163265  4.28571429  4.48979592  4.69387755  4.89795918  5.10204082
   5.30612245  5.51020408  5.71428571  5.91836735]
 [ 6.12

In [26]:
import numpy as np
a=np.random.random((12))
A=a.reshape(3,4)
print(A)
print(A.transpose())

[[0.89113397 0.15700692 0.54922493 0.72604035]
 [0.83390467 0.85096799 0.28527439 0.48037676]
 [0.23950201 0.4602215  0.95444063 0.15078256]]
[[0.89113397 0.83390467 0.23950201]
 [0.15700692 0.85096799 0.4602215 ]
 [0.54922493 0.28527439 0.95444063]
 [0.72604035 0.48037676 0.15078256]]
