<a href="https://colab.research.google.com/github/gouravsingh2009/DECISION-TREE-ALGO-/blob/main/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
pip install numpy
import numpy as np 
from numpy import *

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [13]:
a = array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [17]:
b= array(([1,2,3],[4,5,6]))
print(b)

[[1 2 3]
 [4 5 6]]


In [22]:
c =array([[[1,2,3],[1,2]],[[5,7,9],[2,8]]])
print(c)

<ipython-input-22-db9bedc6d192>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c =array([[[1,2,3],[1,2]],[[5,7,9],[2,8]]])


Check Number of Dimensions 

In [37]:
a = array(42)
b = array([1, 2, 3, 4, 5])
c = array([[1, 2, 3], [4, 5, 6]])
d = array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [40]:
arr = array([1, 2, 3, 4], ndmin=2)

print(arr)
print('number of dimensions :', arr.ndim)

[[1 2 3 4]]
number of dimensions : 2


In [47]:
print(d[0])
print(b[0])
print(c[1])

[[1 2 3]
 [4 5 6]]
1
[4 5 6]


Access elements in a multidimensional array 

In [48]:
print(d[0,1])

[4 5 6]


In [50]:
arr = array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


NEGATIVE INDEXING ( Using above array ' arr' .)

In [51]:
print(arr[1,-3])

8


Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [58]:
d = array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d[1:])
print(d[0:1])
print(d[:3])

[[[1 2 3]
  [4 5 6]]]
[[[1 2 3]
  [4 5 6]]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [73]:
a= array([1,2,3,4,5,6,7,9])
print(a[4:7])
print(a[2:])
print(a[:5])
print(a[2:7:2])
print(a[-7:-1:2])
print(a[::3])

[5 6 7]
[3 4 5 6 7 9]
[1 2 3 4 5]
[3 5 7]
[2 4 6]
[1 4 7]


Slicing in 2 D Arrays 

In [75]:
arr = array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

arr = array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[3 8]
[[2 3 4]
 [7 8 9]]


In [12]:
import numpy as np

arr_zeros= np.zeros(3)
arr_zeros


array([0., 0., 0.])

In [11]:
arr_ones= np.ones([3,3])
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr_empty= np.empty(5)
arr_empty

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
new_arr= np.arange(10)
print(new_arr)

[0 1 2 3 4 5 6 7 8 9]


Shape Manipulations